"""initial schema

Revision ID: f366d1b12df7
Revises: 
Create Date: 2026-09-07 14:50:00.169392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f366d1b12df7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='formstatus', native_enum=False, length=20), nullable=False),
    sa.Column('public_slug', sa.String(length=64), nullable=True),
    sa.Column('theme_config', sa.JSON(), nullable=True),
    sa.Column('thank_you_title', sa.String(length=255), nullable=True),
    sa.Column('thank_you_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forms_public_slug'), ['public_slug'], unique=True)

    op.create_table('form_responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('form_id', sa.String(length=36), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('completion_time_seconds', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('form_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_form_responses_form_id'), ['form_id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('form_id', sa.String(length=36), nullable=False),
    sa.Column('question_text', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('question_type', sa.Enum('SHORT_TEXT', 'LONG_TEXT', 'MULTIPLE_CHOICE', 'DROPDOWN', 'EMAIL', 'NUMBER', 'YES_NO', 'RATING', name='questiontype', native_enum=False, length=30), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_form_id'), ['form_id'], unique=False)

    op.create_table('answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('response_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('answer_value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['form_responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answers_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answers_response_id'), ['response_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answers_response_id'))
        batch_op.drop_index(batch_op.f('ix_answers_question_id'))

    op.drop_table('answers')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_form_id'))

    op.drop_table('questions')
    with op.batch_alter_table('form_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_form_responses_form_id'))

    op.drop_table('form_responses')
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forms_public_slug'))

    op.drop_table('forms')
    # ### end Alembic commands ###
